server.port=${PORT:8080}
server.servlet.context-path=/api
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.zmwkizzidqvqeebyxhpo
spring.datasource.password=FtNv1aANIOrhFCHD
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate  # Not update in prod
spring.jpa.show-sql=false
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
